### PR TITLE
Removing "Data" wrapper for logrus entry keys

### PR DESCRIPTION
**Pull request by leogaona-luizalabs**
I believe it makes more sense to generate the doc without the Data wrapper element. Just trying to help ;)

### CODE REVIEW

**Comment by gerep** [comment]
I like this approach because it keeps the basic info as is and also removes the unnecessary `data` property from the logs.

**Comment by macnibblet** [comment]
Looks good to me, any specific reason you were looking into this?

**Comment by leogaona-luizalabs** [comment]
Not at all. We just have another kind of hook here at Magazine Luiza and we thought it would be good for the elasticsearch hook to generate documents in the same format.

Thanks for accepting the PR

**Comment by macnibblet** [comment]
Makes sense 👍

**Comment by macnibblet** [comment]
@leogaona-luizalabs I'm going to have to revert this or change it. This is actually causing panics when it comes to high concurrency projects.

**Comment by leogaona-luizalabs** [comment]
Really? Sorry to hear that :(

Feel free to revert it, I'll think of another approach and send another PR in the future. Just to clarify: The panics are concurrent map write?

**Comment by macnibblet** [comment]
@leogaona-luizalabs Already pushed a fix, you should update to `1.0.2`. 

And yes, it's concurrent read/write from adding those properties to `entry.Data` previously. So I just created a simple map of type `map[string]interface{}` and added everything to it. Should be consistent with the data in elasticsearch of the previous fix.

**Comment by leogaona-luizalabs** [comment]
Thanks and sorry for the mess!

**Pull request merged**
